added bookings
Brotholomew/flatly pull request #35
Opened 2021-12-21 19:05 UTC by A-Gajda

2021-12-29 09:13 UTC, Brotholomew approved these changes

2021-12-30 09:28 UTC, RazorMeister requested changes

2021-12-30 09:28 UTC, RazorMeister commented on src/common/types/Booking.ts
> +export const EmptyRenter: Renter = {
Z racji ze nie bedziemy tworzyc nowych bookingow te stale nie sa potrzebne

2021-12-30 09:28 UTC, RazorMeister commented on src/common/types/Booking.ts
> +export const EmptyBooking: Booking = {
to co wyżej

2021-12-30 09:28 UTC, RazorMeister commented on src/components/bookings/BookingListItem.tsx
> +    const handleEditClick = () => {
edycja nie jest potrzebna

2022-01-02 17:42 UTC, kowalakk commented on src/common/types/Booking.ts
> +export const EmptyRenter: Renter = {
Usunąłem

2022-01-02 17:42 UTC, kowalakk commented on src/common/types/Booking.ts
> +export const EmptyBooking: Booking = {
Usunąłem

2022-01-02 17:42 UTC, kowalakk commented on src/components/bookings/BookingListItem.tsx
> +    const handleEditClick = () => {
Usunąłem

2022-01-02 17:44 UTC, kowalakk approved these changes

2022-01-03 17:54 UTC, RazorMeister approved these changes

2022-01-03 18:03 UTC, merged