added pagination component
Brotholomew/flatly pull request #37
Opened 2021-12-28 12:31 UTC by Brotholomew

1. added redux reducers, actions and types to strore pagination state
2. added a reusable pagination component (just add new values into store reducers)
3. updated flats list to use pagination at the bottom

Signed-off-by: Bartosz Błachut <bartoszek.blach@gmail.com>

2021-12-30 09:34 UTC, lavar3l approved these changes

2021-12-30 09:45 UTC, RazorMeister requested changes

2021-12-30 09:45 UTC, RazorMeister commented on src/store/modules/pagination/reducers.ts
> +    let payload;
czy ta zmienna jest tu niezbedna? Bo z tego co widze to mozesz uzyc bezposrednio action.payload

2021-12-30 09:45 UTC, RazorMeister commented on src/store/modules/pagination/types.ts
> +export const FLATS = 'FLATS'
Nie lepiej byloby nazwa FLATS_CURRENT_PAGE, FLATS_MAX_PAGE?

2021-12-30 09:45 UTC, RazorMeister commented on src/modules/useFlats.ts
> +            return FlatService.index(page === null ? null : {page: page})
jesli w obiekcie przekazesz { page } to on automatycznie zamienia to na { page: page } wiec wystarczy:
page=== null  ? null : { page }

2021-12-30 09:45 UTC, RazorMeister commented on src/modules/useFlats.ts
> +                    let maxPage = res.pagination.totalPages;
w js nie uzywa sie praktycznie let jesli nie musisz (tak jak w tym przypadku). Wartosc zmiennej sie nie zmienia wiec powinien byc const

2022-01-06 18:49 UTC, RazorMeister approved these changes

2022-01-06 18:50 UTC, merged