Almost works with API
Brotholomew/flatly pull request #44
Opened 2022-01-07 20:29 UTC by kowalakk

Fixed errors, added booking canceling and made almost work with current API. I suppose API needs a small change.

Signed-off-by: Konrad Kowalak bartoszek.blach@gmail.com

2022-01-07 20:36 UTC, RazorMeister requested changes

2022-01-07 20:36 UTC, RazorMeister commented on src/components/popup/cancelPopup.tsx
> +        [
Za dużo duplikacji kodu, przyciski różnia się tylko property click i disabled w jdeym buttonie

2022-01-07 20:36 UTC, RazorMeister commented on src/components/popup/cancelPopup.tsx
> +                        <Picture />
Flatsy maja juz zdjecia wiec mozesz tutaj dodac pierwsze zdjecie

2022-01-20 12:56 UTC, Brotholomew commented on src/components/popup/cancelPopup.tsx
> +        [
done

2022-01-20 12:56 UTC, Brotholomew commented on src/components/popup/cancelPopup.tsx
> +                        <Picture />
done

2022-01-20 12:58 UTC, Brotholomew approved these changes

2022-01-20 16:04 UTC, RazorMeister approved these changes

2022-01-20 16:12 UTC, merged